"""
apply_smoke_degradation.py
==========================
Physics-based atmospheric scattering degradation of laparoscopic video
sequences using a precomputed Navier-Stokes smoke flux field.

Scientific context
------------------
Surgical smoke induced by electrocautery instruments is modelled via the
Koschmieder atmospheric scattering equation:

    f(x,y) = J(x,y) · T(x,y) + A · (1 - T(x,y))

where:
  f(x,y)  — observed degraded laparoscopic frame
  J(x,y)  — latent smoke-free radiance field (reference frame)
  T(x,y)  — spatially varying transmission map in [0, 1]
             T = 0: fully opaque (dense smoke)
             T = 1: fully transparent (no smoke)
  A       — scalar ambient light coefficient (airlight)

The transmission map is derived from the smoke flux field rho(x,y,t)
produced by smoke_simulation.py via Beer-Lambert attenuation:

    T(x,y,t) = exp(-rho(x,y,t) * depth)

where depth is a constant representing the effective optical path length
within the laparoscopic working space.

For each frame k, the script:
  1. Reads the corresponding reference laparoscopic frame from ref_vid.mp4.
  2. Resizes the smoke flux field rho[k] to the target output resolution.
  3. Computes the transmission map T[k] via Beer-Lambert attenuation.
  4. Applies the atmospheric scattering equation to produce the degraded frame.
  5. Writes the degraded frame, transmission map, and reference frame to
     separate output video files.
  6. Saves degraded frames and transmission maps as NumPy arrays (.npy)
     for use as training data by build_dataset.py.

Pipeline position
-----------------
  smoke_simulation.py  →  smoke_flux.npy
                                ↓
                   apply_smoke_degradation.py
                                ↓
             {degraded .mp4, transmission .mp4,
              reference .mp4, .npy arrays}
                                ↓
                       build_dataset.py

Prerequisites
-------------
  - smoke_flux.npy generated by smoke_simulation.py
  - ref_vid.mp4: reference laparoscopic video (no surgical smoke)
    Frame naming convention: frames must be sequentially ordered
    (e.g., frame_1.png, frame_2.png, ...) if assembling from images.
  - pip install numpy opencv-python imageio

Reference
---------
  Diaz-Ramirez et al., "Nonhomogeneous smoke mitigation in laparoscopic
  images using a hybrid physical-neural model", Medical & Biological
  Engineering & Computing, Springer Nature, 2025. (Under review.)

Usage
-----
  python apply_smoke_degradation.py \
      --flux     smoke_flux.npy \
      --video    raw_video/ref_vid.mp4 \
      --output   output/ \
      --sequence 1 \
      --depth    0.25 \
      --airlight 240 \
      --width    512 \
      --fps      5
"""

import os
import argparse
import cv2
import numpy as np


# =============================================================================
# 1. Atmospheric scattering degradation
# =============================================================================

def apply_scattering(
    frame_rgb  : np.ndarray,
    flux       : np.ndarray,
    depth      : float,
    airlight   : float,
    target_w   : int,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Apply the Koschmieder atmospheric scattering model to a single frame.

    Computes the transmission map from the smoke flux field via Beer-Lambert
    attenuation and produces a synthetically degraded frame by applying the
    atmospheric scattering equation channel-wise.

    Parameters
    ----------
    frame_rgb  : np.ndarray, shape (H, W, 3), dtype uint8
        Reference laparoscopic frame in RGB format, cropped to target_w.
    flux       : np.ndarray, shape (N, N), dtype float32
        Smoke density flux field rho(x,y) for the current timestep,
        produced by smoke_simulation.py.
    depth      : float
        Effective optical path length constant. Controls overall smoke
        opacity: larger values produce denser degradation.
        Recommended range: [0.1, 0.5]. Default: 0.25.
    airlight   : float
        Scalar ambient light coefficient A in [0, 255]. Represents the
        intensity of scattered light reaching the camera.
        Recommended range: [200, 250]. Default: 240.
    target_w   : int
        Target output frame width in pixels. The flux field is bilinearly
        resized to (target_w, H) before computing the transmission map.

    Returns
    -------
    degraded_u8 : np.ndarray, shape (H, target_w, 3), dtype uint8
        Synthetically smoke-degraded frame in RGB format.
    trans_u8    : np.ndarray, shape (H, target_w), dtype uint8
        Transmission map T(x,y) scaled to [0, 255] for storage and
        visualization. T=255 corresponds to fully transparent (no smoke).
    """
    H = frame_rgb.shape[0]

    # Resize flux field to target output resolution via bilinear interpolation
    flux_resized = cv2.resize(
        flux, (target_w, H), interpolation=cv2.INTER_LINEAR
    )
    # Scale flux to match training dataset density range
    flux_scaled = 25.0 * flux_resized

    # Beer-Lambert transmission map: T = exp(-rho * depth)
    T = np.exp(-flux_scaled * depth)                      # float32, [0, 1]

    # Atmospheric scattering equation applied per channel
    frame_f = frame_rgb.astype(np.float32)
    degraded = frame_f * T[:, :, np.newaxis] + airlight * (1.0 - T[:, :, np.newaxis])

    degraded_u8 = np.clip(degraded, 0.0, 255.0).astype(np.uint8)
    trans_u8    = np.clip(255.0 * T, 0.0, 255.0).astype(np.uint8)

    return degraded_u8, trans_u8


# =============================================================================
# 2. Main processing loop
# =============================================================================

def process(args: argparse.Namespace) -> None:
    """
    Apply smoke degradation to a reference laparoscopic video sequence.

    Reads the precomputed smoke flux field and the reference video,
    applies the atmospheric scattering model frame by frame, and writes
    the degraded sequence, transmission map sequence, and reference
    sequence as output .mp4 files and .npy arrays.
    """
    os.makedirs(args.output, exist_ok=True)

    # -------------------------------------------------------------------------
    # Load smoke flux field
    # -------------------------------------------------------------------------
    if not os.path.exists(args.flux):
        raise FileNotFoundError(
            f"Smoke flux file not found: {args.flux}\n"
            f"Run smoke_simulation.py first to generate smoke_flux.npy."
        )
    b_flux = np.load(args.flux)                           # (steps, N, N)
    n_flux = b_flux.shape[0]
    print(f"Smoke flux loaded  : {args.flux}  (shape: {b_flux.shape})")

    # -------------------------------------------------------------------------
    # Open reference video
    # -------------------------------------------------------------------------
    cap = cv2.VideoCapture(args.video)
    if not cap.isOpened():
        raise FileNotFoundError(
            f"Reference video not found: {args.video}"
        )
    n_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    W_orig   = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    H        = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    print(f"Reference video    : {args.video}  "
          f"({n_frames} frames, {H}×{W_orig})")

    # Determine processing length: minimum of flux steps and video frames
    n_process = min(n_flux, n_frames)
    target_w  = args.width
    print(f"Output resolution  : {H}×{target_w}")
    print(f"Frames to process  : {n_process}")
    print(f"Depth              : {args.depth}")
    print(f"Airlight           : {args.airlight}")

    # -------------------------------------------------------------------------
    # Output video writers (cross-platform mp4v codec)
    # -------------------------------------------------------------------------
    seq_id  = str(args.sequence)
    fourcc  = cv2.VideoWriter_fourcc(*"mp4v")
    size    = (target_w, H)
    fps     = args.fps

    path_deg   = os.path.join(args.output, f"degraded_sequence{seq_id}.mp4")
    path_trans = os.path.join(args.output, f"transmission_sequence{seq_id}.mp4")
    path_ref   = os.path.join(args.output, f"undegraded_sequence{seq_id}.mp4")

    vid_deg   = cv2.VideoWriter(path_deg,   fourcc, fps, size)
    vid_trans = cv2.VideoWriter(path_trans, fourcc, fps, size)
    vid_ref   = cv2.VideoWriter(path_ref,   fourcc, fps, size)

    # Accumulation arrays for .npy output
    frames_deg   = np.empty((n_process, H, target_w, 3), dtype=np.uint8)
    frames_trans = np.empty((n_process, H, target_w),    dtype=np.uint8)

    # -------------------------------------------------------------------------
    # Frame-level processing
    # -------------------------------------------------------------------------
    for k in range(n_process):
        ret, frame_bgr = cap.read()
        if not ret:
            print(f"Warning: video ended at frame {k}.")
            break

        # Crop reference frame to target width (centre crop)
        left     = (W_orig - target_w) // 2
        frame_bgr = frame_bgr[:, left:left + target_w]
        frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)

        # Apply atmospheric scattering
        degraded_rgb, trans = apply_scattering(
            frame_rgb  = frame_rgb,
            flux       = b_flux[k],
            depth      = args.depth,
            airlight   = args.airlight,
            target_w   = target_w,
        )

        # Convert to BGR for OpenCV writers
        degraded_bgr = cv2.cvtColor(degraded_rgb, cv2.COLOR_RGB2BGR)
        trans_bgr    = cv2.cvtColor(trans,         cv2.COLOR_GRAY2BGR)
        ref_bgr      = cv2.cvtColor(frame_rgb,     cv2.COLOR_RGB2BGR)

        vid_deg.write(degraded_bgr)
        vid_trans.write(trans_bgr)
        vid_ref.write(ref_bgr)

        frames_deg[k]   = degraded_rgb
        frames_trans[k] = trans

        if (k + 1) % 50 == 0 or k == 0:
            T_mean = trans.astype(np.float32).mean() / 255.0
            print(f"  Frame {k+1:4d}/{n_process} | mean T = {T_mean:.3f}")

    # -------------------------------------------------------------------------
    # Release resources
    # -------------------------------------------------------------------------
    cap.release()
    vid_deg.release()
    vid_trans.release()
    vid_ref.release()

    # -------------------------------------------------------------------------
    # Save NumPy arrays for dataset construction pipeline
    # -------------------------------------------------------------------------
    path_npy_deg   = os.path.join(args.output, f"x_deg_frames{seq_id}.npy")
    path_npy_trans = os.path.join(args.output, f"y_trans_frames{seq_id}.npy")
    np.save(path_npy_deg,   frames_deg[:k+1])
    np.save(path_npy_trans, frames_trans[:k+1])

    print(f"\nOutputs written to: {args.output}")
    print(f"  Degraded video        : {path_deg}")
    print(f"  Transmission video    : {path_trans}")
    print(f"  Reference video       : {path_ref}")
    print(f"  Degraded frames (.npy): {path_npy_deg}")
    print(f"  Transmission  (.npy)  : {path_npy_trans}")
    print(f"  Frames processed      : {k+1}")


# =============================================================================
# Entry point
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Apply physics-based atmospheric scattering degradation to a "
            "reference laparoscopic video using a precomputed smoke flux field."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--flux",     type=str,   default="smoke_flux.npy",
                        help="Path to smoke flux .npy file (from smoke_simulation.py).")
    parser.add_argument("--video",    type=str,   default="raw_video/ref_vid.mp4",
                        help="Path to reference laparoscopic video (.mp4, no smoke).")
    parser.add_argument("--output",   type=str,   default="output/",
                        help="Output directory for degraded sequences.")
    parser.add_argument("--sequence", type=int,   default=1,
                        help="Sequence index used in output filenames.")
    parser.add_argument("--depth",    type=float, default=0.25,
                        help="Beer-Lambert optical depth constant.")
    parser.add_argument("--airlight", type=float, default=240.0,
                        help="Scalar ambient light coefficient A in [0, 255].")
    parser.add_argument("--width",    type=int,   default=512,
                        help="Output frame width in pixels (centre-cropped).")
    parser.add_argument("--fps",      type=int,   default=5,
                        help="Output video frame rate.")
    return parser.parse_args()


if __name__ == "__main__":
    process(parse_args())
