"""
smoke_simulation.py
===================
Physics-based 2D surgical smoke simulation using the Stable Fluids framework.

Scientific context
------------------
Surgical smoke generated by electrocautery instruments exhibits spatially
nonhomogeneous, temporally dynamic density distributions within the
insufflated abdominal cavity. This module implements a 2D numerical solver
for the incompressible Navier-Stokes equations to model the fluid dynamics
of surgical smoke, producing physically consistent smoke flux fields for
use in synthetic dataset construction.

The solver follows the Stable Fluids formulation (Stam, 1999) and includes:
  - Semi-Lagrangian advection for unconditional numerical stability
  - Implicit viscous diffusion via Gauss-Seidel relaxation
  - Pressure projection to enforce the divergence-free velocity constraint
  - Vorticity confinement to preserve small-scale rotational flow structures
  - Thermal buoyancy to model smoke rise behaviour
  - Combustion and fuel dissipation dynamics

Output
------
The simulation produces a density frame sequence dens_frames of shape
(steps, N, N), representing the spatially varying smoke flux field
rho(x, y, t) at each simulation timestep. This array is saved as
smoke_flux.npy and consumed by apply_smoke_degradation.py to construct
the synthetic degraded laparoscopic image dataset.

Pipeline position
-----------------
  smoke_simulation.py  →  smoke_flux.npy  →  apply_smoke_degradation.py

Prerequisites
-------------
  pip install numpy imageio

Reference
---------
  Diaz-Ramirez et al., "Nonhomogeneous smoke mitigation in laparoscopic
  images using a hybrid physical-neural model", Medical & Biological
  Engineering & Computing, Springer Nature, 2025. (Under review.)

  Stam, J. (1999). Stable fluids. In Proceedings of SIGGRAPH 1999,
  ACM Press/Addison-Wesley, pp. 121-128.

Usage
-----
  python smoke_simulation.py --N 128 --steps 120 --dt 0.15 \
                             --output smoke_flux --fps 24
"""

import argparse
import math
import numpy as np


# =============================================================================
# 1. Grid allocation
# =============================================================================

def alloc(N: int) -> np.ndarray:
    """
    Allocate an (N+2) x (N+2) grid with ghost cells for boundary conditions.

    Parameters
    ----------
    N : int
        Interior grid resolution. Total allocated size is (N+2) x (N+2).

    Returns
    -------
    np.ndarray, shape (N+2, N+2), dtype float32
        Zero-initialized grid.
    """
    return np.zeros((N + 2, N + 2), dtype=np.float32)


# =============================================================================
# 2. Boundary conditions
# =============================================================================

def set_bnd(b: int, x: np.ndarray, N: int) -> None:
    """
    Enforce boundary conditions on a scalar or vector field.

    Parameters
    ----------
    b : int
        Field type selector:
          0 — scalar field (density, temperature, fuel): Neumann (copy)
          1 — x-velocity (u): no-slip on left/right walls, copy on top/bottom
          2 — y-velocity (v): no-slip on top/bottom walls, copy on left/right
    x : np.ndarray, shape (N+2, N+2)
        Field array modified in-place.
    N : int
        Interior grid resolution.
    """
    if b == 1:
        x[1:N+1, 0]   = -x[1:N+1, 1]
        x[1:N+1, N+1] = -x[1:N+1, N]
        x[0,   1:N+1] =  x[1,   1:N+1]
        x[N+1, 1:N+1] =  x[N,   1:N+1]
    elif b == 2:
        x[1:N+1, 0]   =  x[1:N+1, 1]
        x[1:N+1, N+1] =  x[1:N+1, N]
        x[0,   1:N+1] = -x[1,   1:N+1]
        x[N+1, 1:N+1] = -x[N,   1:N+1]
    else:
        x[1:N+1, 0]   = x[1:N+1, 1]
        x[1:N+1, N+1] = x[1:N+1, N]
        x[0,   1:N+1] = x[1,   1:N+1]
        x[N+1, 1:N+1] = x[N,   1:N+1]

    # Corner averaging
    x[0,    0]   = 0.5 * (x[1, 0]   + x[0, 1])
    x[0,    N+1] = 0.5 * (x[1, N+1] + x[0, N])
    x[N+1,  0]   = 0.5 * (x[N, 0]   + x[N+1, 1])
    x[N+1,  N+1] = 0.5 * (x[N, N+1] + x[N+1, N])


# =============================================================================
# 3. Linear solver
# =============================================================================

def lin_solve(b: int, x: np.ndarray, x0: np.ndarray,
              a: float, c: float, N: int, iters: int = 20) -> None:
    """
    Gauss-Seidel iterative relaxation solver for the linear system
    arising from implicit diffusion and pressure projection.

    Parameters
    ----------
    b     : int    — boundary condition selector (passed to set_bnd)
    x     : ndarray — solution field, modified in-place
    x0    : ndarray — right-hand side field
    a     : float  — off-diagonal coefficient
    c     : float  — diagonal coefficient
    N     : int    — interior grid resolution
    iters : int    — number of relaxation iterations (default: 20)
    """
    for _ in range(iters):
        x[1:N+1, 1:N+1] = (x0[1:N+1, 1:N+1] + a * (
            x[1:N+1, 0:N]   + x[1:N+1, 2:N+2] +
            x[0:N,   1:N+1] + x[2:N+2, 1:N+1]
        )) / c
        set_bnd(b, x, N)


# =============================================================================
# 4. Diffusion
# =============================================================================

def diffuse(b: int, x: np.ndarray, x0: np.ndarray,
            diff: float, dt: float, N: int, iters: int = 20) -> None:
    """
    Implicit viscous diffusion of field x with source x0.

    Solves: (I - diff * dt * N^2 * Laplacian) x = x0
    via Gauss-Seidel relaxation, ensuring unconditional stability.

    Parameters
    ----------
    b    : int    — boundary condition selector
    x    : ndarray — output field, modified in-place
    x0   : ndarray — input (source) field
    diff : float  — diffusion coefficient
    dt   : float  — timestep
    N    : int    — interior grid resolution
    iters: int    — solver iterations (default: 20)
    """
    if diff == 0.0:
        x[1:N+1, 1:N+1] = x0[1:N+1, 1:N+1]
        set_bnd(b, x, N)
        return
    a = dt * diff * N * N
    lin_solve(b, x, x0, a, 1 + 4 * a, N, iters)


# =============================================================================
# 5. Advection
# =============================================================================

def advect(b: int, d: np.ndarray, d0: np.ndarray,
           u: np.ndarray, v: np.ndarray,
           dt: float, N: int) -> None:
    """
    Semi-Lagrangian advection of scalar or vector field d.

    For each grid cell (i,j), traces the characteristic backwards in time
    by dt to find the source location, then bilinearly interpolates d0
    at that location. This formulation is unconditionally stable for any
    timestep size.

    Coordinate convention:
      j — column index (x direction, rightward)
      i — row index    (y direction, downward in memory, upward physically)
      u — x-velocity (along j)
      v — y-velocity (along i, positive upward after buoyancy sign convention)

    Parameters
    ----------
    b  : int    — boundary condition selector
    d  : ndarray — output advected field, modified in-place
    d0 : ndarray — input field at previous timestep
    u  : ndarray — x-velocity field
    v  : ndarray — y-velocity field
    dt : float  — timestep
    N  : int    — interior grid resolution
    """
    dt0 = dt * N

    ii = np.arange(1, N+1, dtype=np.float32)[:, None]   # row indices
    jj = np.arange(1, N+1, dtype=np.float32)[None, :]   # col indices

    uij = u[1:N+1, 1:N+1]
    vij = v[1:N+1, 1:N+1]

    # Back-trace source positions
    x = np.clip(jj - dt0 * uij, 0.5, N + 0.5)
    y = np.clip(ii - dt0 * vij, 0.5, N + 0.5)

    j0 = np.floor(x).astype(np.int32);  j1 = j0 + 1
    i0 = np.floor(y).astype(np.int32);  i1 = i0 + 1

    s1 = x - j0;  s0 = 1.0 - s1
    t1 = y - i0;  t0 = 1.0 - t1

    # Bilinear interpolation
    d[1:N+1, 1:N+1] = (
        s0 * (t0 * d0[i0, j0] + t1 * d0[i1, j0]) +
        s1 * (t0 * d0[i0, j1] + t1 * d0[i1, j1])
    )
    set_bnd(b, d, N)


# =============================================================================
# 6. Pressure projection
# =============================================================================

def project(u: np.ndarray, v: np.ndarray,
            p: np.ndarray, div: np.ndarray,
            N: int, iters: int = 20) -> None:
    """
    Project velocity field (u, v) onto the space of divergence-free fields.

    Solves the pressure Poisson equation:
      Laplacian(p) = divergence(u, v)
    then subtracts the pressure gradient from (u, v) to enforce
    the incompressibility constraint: div(u, v) = 0.

    Parameters
    ----------
    u, v : ndarray — velocity fields, modified in-place
    p    : ndarray — pressure field (scratch buffer)
    div  : ndarray — divergence field (scratch buffer)
    N    : int    — interior grid resolution
    iters: int    — solver iterations (default: 20)
    """
    h = 1.0 / N
    div[1:N+1, 1:N+1] = -0.5 * h * (
        u[1:N+1, 2:N+2] - u[1:N+1, 0:N] +
        v[2:N+2, 1:N+1] - v[0:N,   1:N+1]
    )
    p.fill(0.0)
    set_bnd(0, div, N)
    set_bnd(0, p,   N)

    lin_solve(0, p, div, 1.0, 4.0, N, iters)

    u[1:N+1, 1:N+1] -= 0.5 * (p[1:N+1, 2:N+2] - p[1:N+1, 0:N])   / h
    v[1:N+1, 1:N+1] -= 0.5 * (p[2:N+2, 1:N+1] - p[0:N,   1:N+1]) / h
    set_bnd(1, u, N)
    set_bnd(2, v, N)


# =============================================================================
# 7. Vorticity confinement
# =============================================================================

def compute_curl(u: np.ndarray, v: np.ndarray, N: int) -> np.ndarray:
    """
    Compute scalar vorticity omega = dv/dx - du/dy on interior cells.

    Parameters
    ----------
    u, v : ndarray — velocity fields
    N    : int    — interior grid resolution

    Returns
    -------
    np.ndarray, shape (N+2, N+2)
        Vorticity field; only interior cells [1:N+1, 1:N+1] are valid.
    """
    w = np.zeros_like(u)
    w[1:N+1, 1:N+1] = 0.5 * (
        (v[1:N+1, 2:N+2] - v[1:N+1, 0:N]) -
        (u[2:N+2, 1:N+1] - u[0:N,   1:N+1])
    )
    return w


def vorticity_confinement(u: np.ndarray, v: np.ndarray,
                          conf: float, dt: float, N: int) -> None:
    """
    Apply vorticity confinement to counteract numerical dissipation of
    small-scale rotational flow structures.

    Computes the normalized vorticity gradient N = grad(|omega|) / |grad(|omega|)|,
    then applies the confinement force F = epsilon * (N x omega * z_hat)
    to the velocity field.

    Parameters
    ----------
    u, v : ndarray — velocity fields, modified in-place
    conf : float  — confinement coefficient epsilon (0.0 = disabled)
    dt   : float  — timestep
    N    : int    — interior grid resolution
    """
    if conf == 0.0:
        return

    w     = compute_curl(u, v, N)
    abs_w = np.abs(w)

    Nx = np.zeros_like(u)
    Ny = np.zeros_like(v)

    Nx[1:N+1, 1:N+1] = 0.5 * (abs_w[1:N+1, 2:N+2] - abs_w[1:N+1, 0:N])
    Ny[1:N+1, 1:N+1] = 0.5 * (abs_w[2:N+2, 1:N+1] - abs_w[0:N,   1:N+1])

    mag = np.sqrt(Nx**2 + Ny**2) + 1e-6
    Nx /= mag
    Ny /= mag

    u[1:N+1, 1:N+1] += dt * conf *  Ny[1:N+1, 1:N+1] * w[1:N+1, 1:N+1]
    v[1:N+1, 1:N+1] += dt * conf * (-Nx[1:N+1, 1:N+1]) * w[1:N+1, 1:N+1]
    set_bnd(1, u, N)
    set_bnd(2, v, N)


# =============================================================================
# 8. Thermal buoyancy
# =============================================================================

def add_buoyancy(v: np.ndarray, temp: np.ndarray,
                 buoyancy: float, dt: float, N: int) -> None:
    """
    Apply thermal buoyancy to the vertical velocity field.

    Models smoke rise due to thermal expansion:
      v' = v - buoyancy * T * dt
    The negative sign reflects the convention that +v is downward in
    array row indexing, so buoyancy acts upward (negative v).

    Parameters
    ----------
    v        : ndarray — vertical velocity field, modified in-place
    temp     : ndarray — temperature field, normalized to [0, 1]
    buoyancy : float  — buoyancy coefficient (0.0 = disabled)
    dt       : float  — timestep
    N        : int    — interior grid resolution
    """
    if buoyancy == 0.0:
        return
    v[1:N+1, 1:N+1] -= buoyancy * temp[1:N+1, 1:N+1] * dt
    set_bnd(2, v, N)


# =============================================================================
# 9. Combustion and noise dynamics
# =============================================================================

def combustion_step(temp: np.ndarray, fuel: np.ndarray, noise: np.ndarray,
                    dt: float,
                    burn_temperature: float = 1700.0,
                    cooling: float = 3000.0,
                    noise_blending: float = 0.5,
                    fuel_dissipation: float = 0.92,
                    N: int = 64) -> None:
    """
    Advance combustion dynamics by one timestep.

    Models fuel ignition, temperature evolution under radiative cooling
    (Stefan-Boltzmann T^4 law), and fuel dissipation. Noise blending
    introduces stochastic perturbations to the effective fuel efficiency,
    producing realistic irregular smoke density variations.

    Parameters
    ----------
    temp             : ndarray — temperature field [0,1], modified in-place
    fuel             : ndarray — fuel density field [0,1], modified in-place
    noise            : ndarray — stochastic noise field [0,1]
    dt               : float  — timestep
    burn_temperature : float  — peak combustion temperature (unused scalar,
                                retained for interface compatibility)
    cooling          : float  — radiative cooling rate coefficient
    noise_blending   : float  — noise influence on fuel efficiency [0,1]
    fuel_dissipation : float  — per-frame fuel decay factor [0,1]
    N                : int    — interior grid resolution
    """
    f = np.clip(fuel, 0.0, 1.0)
    t = np.clip(temp, 0.0, 1.0)
    n = np.clip(noise, 0.0, 1.0)

    fuel_eff = f * (1.0 - 0.3 * noise_blending + 0.3 * n * noise_blending)
    t_new    = np.maximum(t, fuel_eff)

    sigma = 1.0 / max(cooling, 1.0) * 8.0
    t_new = np.clip(t_new - sigma * (t_new ** 4) * dt, 0.0, 1.0)
    f_new = np.clip(f * (fuel_dissipation ** (dt / 0.016)), 0.0, 1.0)

    temp[1:N+1, 1:N+1] = t_new[1:N+1, 1:N+1]
    fuel[1:N+1, 1:N+1] = f_new[1:N+1, 1:N+1]


def update_noise(noise: np.ndarray, dt: float,
                 volatility: float, N: int) -> None:
    """
    Update the stochastic noise field by adding uniform random perturbations.

    Parameters
    ----------
    noise      : ndarray — noise field [0,1], modified in-place
    dt         : float  — timestep
    volatility : float  — perturbation magnitude per unit time (0.0 = disabled)
    N          : int    — interior grid resolution
    """
    if volatility <= 0.0:
        return
    rand = np.random.uniform(-1.0, 1.0, size=noise.shape).astype(np.float32)
    noise[1:N+1, 1:N+1] = np.clip(
        noise[1:N+1, 1:N+1] + volatility * dt * rand[1:N+1, 1:N+1],
        0.0, 1.0
    )


# =============================================================================
# 10. Top-level simulation
# =============================================================================

# Default fluid dynamics configuration used in the manuscript experiments.
DEFAULT_CONFIG = {
    "BUOYANCY":            0.2,
    "BURN_TEMPERATURE":    1700.0,
    "CONFINEMENT":         5.0,
    "COOLING":             1000.0,
    "DENSITY_DISSIPATION": 0.999,
    "FUEL_DISSIPATION":    0.92,
    "NOISE_BLENDING":      0.5,
    "NOISE_VOLATILITY":    0.1,
    "PRESSURE_DISSIPATION":0.8,
    "VELOCITY_DISSIPATION":0.98,
}


def simulate(
    N        : int             = 128,
    steps    : int             = 120,
    dt       : float           = 0.15,
    config   : dict | None     = None,
    emissions: list[dict]| None= None,
) -> np.ndarray:
    """
    Run the 2D Navier-Stokes surgical smoke simulation.

    Produces a temporally dynamic, spatially nonhomogeneous smoke density
    field rho(x, y, t) by advancing the fluid state for `steps` timesteps.
    Each emission event injects density, fuel, temperature, and impulse
    into a circular region of the domain, modelling the spatial onset of
    electrocautery-generated surgical smoke associated with instrument
    contact points.

    Parameters
    ----------
    N         : int
        Interior grid resolution (N x N). Default: 128.
    steps     : int
        Number of simulation timesteps. Default: 120.
    dt        : float
        Simulation timestep. Default: 0.15.
    config    : dict or None
        Fluid dynamics parameter dictionary. If None, DEFAULT_CONFIG is used.
        Keys: BUOYANCY, BURN_TEMPERATURE, CONFINEMENT, COOLING,
              DENSITY_DISSIPATION, FUEL_DISSIPATION, NOISE_BLENDING,
              NOISE_VOLATILITY, PRESSURE_DISSIPATION, VELOCITY_DISSIPATION.
    emissions : list of dict or None
        List of smoke emission event specifications. Each entry is a dict
        with the following keys:
          when     : int   — timestep at which emission begins
          duration : int   — number of timesteps the emission is active
          center   : tuple — (x, y) emission origin in [0,1]^2,
                             x: 0=left, 1=right; y: 0=bottom, 1=top
          radius   : float — emission region radius as fraction of domain [0,1]
          density  : float — smoke density injection rate
          fuel     : float — fuel injection rate
          heat     : float — temperature injection rate
          impulse  : tuple — (u, v) velocity impulse at emission point

    Returns
    -------
    dens_frames : np.ndarray, shape (steps, N, N), dtype float32
        Smoke density flux field rho(x, y, t) at each timestep.
        Values are non-negative; density scale depends on emission parameters.
        This array is saved as smoke_flux.npy by save_flux().
    """
    if config is None:
        config = DEFAULT_CONFIG
    if emissions is None:
        emissions = []

    # Field allocation
    u,  v   = alloc(N), alloc(N)
    u0, v0  = alloc(N), alloc(N)
    dens,  dens0  = alloc(N), alloc(N)
    fuel,  fuel0  = alloc(N), alloc(N)
    temp,  temp0  = alloc(N), alloc(N)
    noise, noise0 = alloc(N), alloc(N)
    p,     div    = alloc(N), alloc(N)

    # Grid coordinate arrays (used for circular emission masks)
    yy, xx = np.mgrid[0:N+2, 0:N+2]

    dens_frames = np.empty((steps, N, N), dtype=np.float32)

    for t in range(steps):
        u0.fill(0.0);  v0.fill(0.0)
        dens0.fill(0.0); fuel0.fill(0.0); temp0.fill(0.0)
        noise0.fill(0.0)

        # --- Apply emission events ---
        for e in emissions:
            start = int(e.get("when", 0))
            dur   = int(e.get("duration", 1))
            if not (start <= t < start + dur):
                continue

            cx, cy    = e.get("center", (0.5, 0.1))
            radius    = float(e.get("radius", 0.1))
            dens_add  = float(e.get("density", 1.0))
            fuel_add  = float(e.get("fuel",    dens_add))
            heat_add  = float(e.get("heat",    dens_add))
            u_imp, v_imp = e.get("impulse", (0.0, 0.0))

            # Map [0,1] domain coordinates to grid indices
            # x: 0=left → j=1, 1=right → j=N
            # y: 0=bottom → i=N (flipped), 1=top → i=1
            gx = int(np.clip(1 + cx * (N - 1), 1, N))
            gy = int(np.clip(1 + (1.0 - cy) * (N - 1), 1, N))
            r  = max(1, int(radius * (N - 1)))

            mask = (xx - gx)**2 + (yy - gy)**2 <= r * r
            dens0[mask] += dens_add
            fuel0[mask] += fuel_add
            temp0[mask] += heat_add
            u0[mask]    += u_imp
            v0[mask]    += v_imp

        # --- Fluid state update ---
        u    += dt * u0
        v    += dt * v0
        dens += dt * dens0
        fuel += dt * fuel0
        temp += dt * temp0

        combustion_step(
            temp, fuel, noise, dt=dt,
            burn_temperature  = config["BURN_TEMPERATURE"],
            cooling           = config["COOLING"],
            noise_blending    = config["NOISE_BLENDING"],
            fuel_dissipation  = config["FUEL_DISSIPATION"],
            N                 = N,
        )

        # Velocity advection and dissipation
        u0[:, :] = u;  v0[:, :] = v
        advect(1, u, u0, u0, v0, dt, N)
        advect(2, v, v0, u0, v0, dt, N)
        u[1:N+1, 1:N+1] *= config["VELOCITY_DISSIPATION"]
        v[1:N+1, 1:N+1] *= config["VELOCITY_DISSIPATION"]
        set_bnd(1, u, N)
        set_bnd(2, v, N)

        vorticity_confinement(u, v, conf=config["CONFINEMENT"], dt=dt, N=N)
        add_buoyancy(v, temp, buoyancy=config["BUOYANCY"], dt=dt, N=N)
        project(u, v, p, div, N=N, iters=20)

        # Scalar field advection and dissipation
        dens0[:, :] = dens
        advect(0, dens, dens0, u, v, dt, N)
        dens[1:N+1, 1:N+1] *= config["DENSITY_DISSIPATION"]

        temp0[:, :] = temp
        advect(0, temp, temp0, u, v, dt, N)

        fuel0[:, :] = fuel
        advect(0, fuel, fuel0, u, v, dt, N)
        fuel[1:N+1, 1:N+1] *= config["FUEL_DISSIPATION"]

        noise0[:, :] = noise
        advect(0, noise, noise0, u, v, dt, N)
        update_noise(noise, dt, config["NOISE_VOLATILITY"], N)

        np.clip(dens,  0.0, None, out=dens)
        np.clip(temp,  0.0, 1.0,  out=temp)
        np.clip(fuel,  0.0, 1.0,  out=fuel)
        np.clip(noise, 0.0, 1.0,  out=noise)

        dens_frames[t] = dens[1:N+1, 1:N+1]

    return dens_frames


# =============================================================================
# 11. Output
# =============================================================================

def save_flux(dens_frames: np.ndarray,
              output_path: str = "smoke_flux",
              fps: int = 24,
              gain: float = 3.0,
              gamma: float = 0.9) -> None:
    """
    Save the smoke flux field as a NumPy binary array and an optional GIF
    for visual inspection.

    Parameters
    ----------
    dens_frames : np.ndarray, shape (steps, N, N)
        Smoke density flux array produced by simulate().
    output_path : str
        Output file path without extension. Produces:
          {output_path}.npy  — binary array consumed by apply_smoke_degradation.py
          {output_path}.gif  — visual preview (requires imageio)
    fps   : int   — GIF frame rate (default: 24)
    gain  : float — contrast gain for GIF visualization (default: 3.0)
    gamma : float — gamma correction for GIF visualization (default: 0.9)
    """
    np.save(output_path + ".npy", dens_frames)
    print(f"Smoke flux saved to: {output_path}.npy  "
          f"(shape: {dens_frames.shape}, dtype: {dens_frames.dtype})")

    try:
        import imageio.v2 as imageio
        f   = np.nan_to_num(dens_frames.astype(np.float32))
        imgs = []
        for k in range(f.shape[0]):
            fk  = f[k]
            mx  = float(np.percentile(fk, 99.0))
            mx  = mx if (np.isfinite(mx) and mx > 1e-6) else 1.0
            g   = np.clip(fk / mx * gain, 0.0, 1.0)
            if gamma > 0:
                g = g ** (1.0 / gamma)
            imgs.append((g * 255.0 + 0.5).astype(np.uint8))
        imageio.mimsave(output_path + ".gif", imgs,
                        duration=1.0 / float(fps))
        print(f"Visual preview saved to: {output_path}.gif")
    except ImportError:
        print("imageio not found — GIF preview skipped. "
              "Install with: pip install imageio")


# =============================================================================
# Entry point
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="2D Navier-Stokes surgical smoke simulation.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--N",      type=int,   default=128,
                        help="Interior grid resolution.")
    parser.add_argument("--steps",  type=int,   default=120,
                        help="Number of simulation timesteps.")
    parser.add_argument("--dt",     type=float, default=0.15,
                        help="Simulation timestep.")
    parser.add_argument("--output", type=str,   default="smoke_flux",
                        help="Output file path (without extension).")
    parser.add_argument("--fps",    type=int,   default=24,
                        help="GIF preview frame rate.")
    parser.add_argument("--gain",   type=float, default=3.0,
                        help="Contrast gain for GIF visualization.")
    parser.add_argument("--gamma",  type=float, default=0.9,
                        help="Gamma correction for GIF visualization.")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()

    # Example emission configuration representing a single electrocautery
    # instrument contact event with nonhomogeneous spatial distribution,
    # consistent with the dataset construction protocol described in the
    # manuscript (Section 3.2).
    emissions = [
        {
            "when": 20, "duration": 10,
            "center": (0.54, 0.55), "radius": 0.11,
            "density": 0.4, "fuel": 1.5, "heat": 1.0,
            "impulse": (0.25, 0.0),
        },
        {
            "when": 35, "duration": 5,
            "center": (0.43, 0.63), "radius": 0.09,
            "density": 0.3, "fuel": 1.5, "heat": 1.0,
            "impulse": (0.0,  0.0),
        },
        {
            "when": 55, "duration": 10,
            "center": (0.34, 0.66), "radius": 0.13,
            "density": 0.27, "fuel": 1.5, "heat": 1.0,
            "impulse": (-0.35, 0.2),
        },
        {
            "when": 72, "duration": 10,
            "center": (0.32, 0.40), "radius": 0.12,
            "density": 0.3, "fuel": 1.5, "heat": 1.0,
            "impulse": (0.2,  0.1),
        },
    ]

    print(f"Running simulation: N={args.N}, steps={args.steps}, dt={args.dt}")
    dens_frames = simulate(
        N=args.N, steps=args.steps, dt=args.dt, emissions=emissions
    )
    save_flux(dens_frames, output_path=args.output,
              fps=args.fps, gain=args.gain, gamma=args.gamma)
    print("Done.")
